#!/usr/bin/env node

"use strict";

var fs = require('fs');
var program = require('commander');
var ncp = require('ncp').ncp;

var version = JSON.parse(fs.readFileSync(__dirname + '/../package.json', 'utf8')).version;
var name = "Maaperture v" + version;
var description = "MongoDB as an Admin Platform - Aperture Software";

function printHelpTitle() {
	console.log('');
	console.log('  --------------------------------------------------');
	console.log('   ' + name);
	console.log('');
	console.log('   ' + description);
	console.log('  --------------------------------------------------');
}

function setProjectName(project_name) {
	//JSON.parse(fs.readFileSync(__dirname + '/../package.json', 'utf8')).version;
}

function initProject(project_name) {
	var source = __dirname + '/../maap_project';
	var destination = './' + project_name;
	var info = "JK rocks!";
	console.log('');
	console.log(name + " - " + description);
	console.log('');
	console.log('generating a new empty project ' + project_name + ' into ' + destination + '...');
	ncp(source, destination, function(err) {
		if(err) {
			return console.error(err);
		}
		setProjectName(project_name);
		console.log('well done!');
		console.log('you are ready to install the dependencies and start the server');
		console.log('with: "cd ' + project_name + ' && npm install && npm start"');
	});	
}

program
	.version(version)
	.usage('[options]')
	.option('-C, --create <project_name>', 'create and initialize a new empty project', initProject)
 
program.on('--help', function(){
  console.log('  Examples:');
  console.log('');
  console.log('    $ maaperture --create razorback');
  console.log('    $ maaperture -C razorback');
  console.log('');
});

program.unknownOption = function(){
	printHelpTitle();
	program.help();
}

program.on('*', function(){
	printHelpTitle();
	program.help();
});

program
	.parse(process.argv);
	
if (process.argv.length === 2) {
	printHelpTitle();
	program.help();
}